Chapter11/myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
                                     name='cart_remove'),
]

Chapter11/myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from payment import webhooks

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)

urlpatterns += [
    path('payment/webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Chapter11/myshop/payment/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

app_name = 'payment'

urlpatterns = [
    path(_('process/'), views.payment_process, name='process'),
    path(_('completed/'), views.payment_completed, name='completed'),
    path(_('canceled/'), views.payment_canceled, name='canceled'),
]

Chapter11/myshop/payment/models.py
from django.db import models

# Create your models here.

Chapter11/myshop/payment/views.py
from decimal import Decimal
import stripe
from django.conf import settings
from django.shortcuts import render, redirect, reverse,\
                             get_object_or_404
from orders.models import Order


# create the Stripe instance
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        success_url = request.build_absolute_uri(
                        reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(
                        reverse('payment:canceled'))

        # Stripe checkout session data
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        # add order items to the Stripe checkout session
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'usd',
                    'product_data': {
                        'name': item.product.name,
                    },
                },
                'quantity': item.quantity,
            })

        # Stripe coupon
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                                name=order.coupon.code,
                                percent_off=order.discount,
                                duration='once')
            session_data['discounts'] = [{
                'coupon': stripe_coupon.id
            }]

        # create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)

        # redirect to Stripe payment form
        return redirect(session.url, code=303)

    else:
        return render(request, 'payment/process.html', locals())


def payment_completed(request):
    return render(request, 'payment/completed.html')


def payment_canceled(request):
    return render(request, 'payment/canceled.html')

Chapter11/myshop/payment/templates/payment/canceled.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block title %}{% trans "Payment canceled" %}{% endblock %}

{% block content %}
  <h1>{% trans "Your payment has not been processed" %}</h1>
  <p>{% trans "There was a problem processing your payment." %}</p>
{% endblock %}

Chapter11/myshop/payment/templates/payment/completed.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block title %}{% trans "Payment successful" %}{% endblock %}

{% block content %}
  <h1>{% trans "Your payment was successful" %}</h1>
  <p>{% trans "Your payment has been processed successfully." %}</p>
{% endblock %}

Chapter11/myshop/payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Pay your order" %}{% endblock %}

{% block content %}
  <h1>{% trans "Order summary" %}</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>{% trans "Image" %}</th>
        <th>{% trans "Product" %}</th>
        <th>{% trans "Price" %}</th>
        <th>{% trans "Quantity" %}</th>
        <th>{% trans "Total" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in order.items.all %}
        <tr class="row{% cycle "1" "2" %}">
          <td>
            <img src="{% if item.product.image %}{{ item.product.image.url }}
            {% else %}{% static "img/no_image.png" %}{% endif %}">
          </td>
          <td>{{ item.product.name }}</td>
          <td class="num">${{ item.price }}</td>
          <td class="num">{{ item.quantity }}</td>
          <td class="num">${{ item.get_cost }}</td>
        </tr>
      {% endfor %}
      {% if order.coupon %}
        <tr class="subtotal">
          <td>{% trans "Subtotal" %}</td>
          <td colspan="3"></td>
          <td class="num">
            ${{ order.get_total_cost_before_discount|floatformat:2 }}
          </td>
        </tr>
        <tr>
          <td>
            {% blocktrans with code=order.coupon.code discount=order.discount %}
              "{{ code }}" ({{ discount }}% off)
            {% endblocktrans %}
          </td>
          <td colspan="3"></td>
          <td class="num neg">
            - ${{ order.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>{% trans "Total" %}</td>
        <td colspan="3"></td>
        <td class="num">
          ${{ order.get_total_cost|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>
  <form action="{% url "payment:process" %}" method="post">
    <input type="submit" value="{% trans "Pay now" %}">
    {% csrf_token %}
  </form>
{% endblock %}